name: Terraform

on:
  push:
    branches:
      - main
      
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5  
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: |
          terraform init
          terraform validate  # Validate Terraform configuration

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var="docker_ssh_key=value" -var="ecr_repository=value"

      - name: Show Terraform Plan Output
        run: echo "${{ steps.plan.outputs.stdout }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="docker_ssh_key=value" -var="ecr_repository=value"
