name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Navigate to Terraform directory
        run: cd terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -config=./main.tf -var docker_ssh_key=my-ssh-key -var ecr_repository_url=***.dkr.ecr.us-east-1.amazonaws.com/nodejs-app -var docker_image_tag=latest -out=tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan

      - name: Destroy Terraform
        if: github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve
