name: Deploy Docker Image on EC2 using Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.4.0'  # Update to a specific, more of predictable and newer version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Initialize Terraform
      run: terraform init
      continue-on-error: true # Continue in case of init errors for debugging

    - name: Plan Terraform
      run: terraform plan -out=tfplan
      continue-on-error: true # Continue in case of plan errors for debugging

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
      continue-on-error: true # Continue in case of apply errors for debugging

    - name: Authenticate Docker to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ***.dkr.ecr.us-east-1.amazonaws.com
      continue-on-error: true

    - name: Build and push Docker image
      run: |
        docker build --tag ***.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest .
        docker push ***.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest
      continue-on-error: true
