name: Deploy Docker Image on EC2 using Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Cache Terraform
      uses: actions/cache@v2
      id: terraform-cache
      key: terraform-cache
      path: ~/.terraform.d/plugin-cache

    - name: Initialize Terraform
      run: terraform init 
      
    - name: Plan Terraform
      run: terraform plan -var docker_ssh_key=my-ssh-key -var ecr_repository_url=***.dkr.ecr.us-east-1.amazonaws.com/nodejs-app -var docker_image_tag=latest -out=tfplan

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
