name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Navigate to Terraform directory
        run: cd terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory:./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
        working-directory:./terraform

      - name: Destroy Terraform
        if: github.ref == 'efs/heads/main'
        run: terraform destroy -auto-approve
        working-directory:./terraform
